name: publish-maven

on:
  workflow_dispatch:
    inputs:
      bucketeer_version:
        description: "Bucketeer version"
        required: true
  push:
    tags:
      - "v*"

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          distribution: "temurin"
          java-version: 17

        # remove 'v' prefix from tag or workflow input
      - name: Determine version
        run: |
          if [ ! -z ${{ github.event.inputs.bucketeer_version }} ]; then
            temp_version="${{ github.event.inputs.bucketeer_version }}"
            result=${temp_version#"v"}
            echo "ORG_GRADLE_PROJECT_VERSION_NAME=${result}" >> $GITHUB_ENV
          else
            temp_version="${{ github.event.ref }}"
            result=${temp_version#"refs/tags/v"}
            echo "ORG_GRADLE_PROJECT_VERSION_NAME=${result}" >> $GITHUB_ENV
          fi

      - name: Publish android-client-sdk
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_RELEASE_SIGNING_ENABLED: true
        run: |
          echo $ORG_GRADLE_PROJECT_VERSION_NAME
          ./gradlew :bucketeer:publishAllPublicationToMavenCentralRepository
