name: Pull Request

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.6.0
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup gradle
        uses: gradle/gradle-build-action@v3

      - name: Ktlint
        run: ./gradlew lintKotlin --stacktrace

      - name: Check Lint
        run: ./gradlew lintDebug --stacktrace

      - name: Build all build types
        run: ./gradlew assemble --stacktrace

      - name: Run Bucketeer unit tests
        run: ./gradlew :bucketeer:testDebugUnitTest --stacktrace

      - name: upload bucketeer build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bucketeer-build-reports
          path: bucketeer/build/reports

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -XX:MetaspaceSize=1g"
