name: Pull Request

on:
  pull_request:
    paths-ignore:
      - '*.md'
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Ktlint
        run: ./gradlew lintKotlin --stacktrace

      - name: Check Lint
        run: ./gradlew lintDebug --stacktrace

      - name: Build all build types
        run: ./gradlew assemble --stacktrace

      - name: Run Bucketeer unit tests
        run: ./gradlew :bucketeer:testDebugUnitTest --stacktrace

      - name: upload bucketeer build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bucketeer-build-reports
          path: bucketeer/build/reports


  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install commitlint
        run: npm install @commitlint/cli @commitlint/config-conventional

      - name: Check commit messages
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.configureondemand=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError -XX:MetaspaceSize=1g"
